### ISSUE TITLE
项目引入组件  没有样式

### ISSUE THREAD

**Issue by linktoword** [AugustinRibreau/vue3-organization-chart#1]
![image](https://user-images.githubusercontent.com/37545695/159664720-b2aadfec-79f9-49c8-83e9-934c9dd1007d.png)

**Comment by sitherine** [comment]
I have the same problem

**Comment by AugustinRibreau** [comment]
I will look into this as soon as possible. Otherwise you can make a pull request

**Comment by AugustinRibreau** [comment]
@linktoword @sitherine Can you confirm that this is good for you? 

The problem was the CSS. I happen to be a regular user of TailwindCSS which is a really great tool. But, it wasn't taken into account in the component build, so I had to switch back to pure CSS.
